on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
